App\Entity\Location:
  properties:
    city:
      - NotBlank: { message: 'City name cannot be empty' }
      - Length:
          min: 2
          max: 255
          minMessage: 'City name must be at least {{ limit }} characters long'
          maxMessage: 'City name cannot be longer than {{ limit }} characters long'

    country:
      - NotBlank: { message: 'Country must be selected' }
      - Length:
          min: 2
          max: 2
          exactMessage: 'The country code must be exactly 2 characters long'

    latitude:
      - NotBlank: { message: 'Latitude is required' }
      - Range:
          min: -90
          max: 90
          notInRangeMessage: 'Latitude must be between -90 and 90 degrees'

    longitude:
      - NotBlank: { message: 'Longitude is required' }
      - Range:
          min: -180
          max: 180
          notInRangeMessage: 'Longitude must be between -180 and 180 degrees'

